
-- Find total customers by countries
select
     country,
     count (customer_key) as total_customers
from Gold.dimension_customers
group by country
order by total_customers desc

-- Find total customers by gender
select
     gender,
     count (customer_key) as total_customers
from Gold.dimension_customers
group by gender
order by total_customers desc

-- Find total products by category
select
     category,
     count (product_key) as total_product
from Gold.dimension_products
group by category
order by total_product desc

-- what is the avg costs in each category?
select
     category,
     avg(cost) as avg_cost
from Gold.dimension_products
group by category
order by avg_cost desc

-- What is the total revenue generated for each category?
select
     p.category,
     sum(f.sales_amount) total_revenue
from Gold.fact_sales f
left join Gold.dimension_products p
on p.product_key = f.product_key
group by p.category
order by total_revenue desc

-- what is the total revenue is generated by each customer?
select 
     c.customer_key,
     c.first_name,
     c.last_name,
     sum(f.sales_amount) as total_revenue
from Gold.fact_sales f
left join Gold.dimension_customers c
on c.customer_key = f.customer_key
group by
     c.customer_key,
     c.first_name,
     c.last_name
order by total_revenue desc


-- what is the distribution of sold items across countries?
select 
     c.country,
     sum(f.quantity) as total_sold_items
from Gold.fact_sales f
left join Gold.dimension_customers c
on c.customer_key = f.customer_key
group by
     c.country
order by total_sold_items desc

